### ISSUE TITLE
# Node Functions

### ISSUE THREAD

**Issue by efraim-andrade** [efraim-andrade/fatecanos-app#5]
---
## Funções
- [x] fatec-api
    - [x] accountLoggedIn()
    - [x] userInfo()
    - [x] geralInfo()
    - [x] courseInfo()
---
- [x] computed data
   - [x] getMaxSkipClass()
---
- [x] Firebase
   - [x] storeDataInFirebase()
   - [x] updateDataInFirebase()

**Comment by cmpsleo** [comment]
ja terminou?

**Comment by efraim-andrade** [comment]
ta quase
